### ISSUE TITLE
Avatar image issues

### ISSUE THREAD

**Issue by yswery** [steveclifton/ArcheryOSA#1]
when registering the default avatar is not loaded in the file system.

It shows path `/image/avatargrey160x160.png` thats not there...

And also after uploading a new image it saves in `public/content/profile/` which is great, however you need to include a .gitignore in there so you dont start checking in images into the repo.

**Comment by yswery** [comment]
example of this `1505033475.jpg` should not be part of the repo.

remove the `1505033475.jpg` file and commit that change and then add a new file into that folder `.gitignore` which should have the content as follows:


```
!.gitignore
```

This means everything will be ignored EXCEPT the actual .gitignore file itself

**Comment by yswery** [comment]
Also on this topic: https://github.com/steveclifton/ArcheryOSA/blob/master/app/Http/Controllers/UserController.php#L115

it will be wise to change 

```
time() . '.' . $image->getClientOriginalExtension();
```

to something like 

```
time() .rand(0,999). '.' . $image->getClientOriginalExtension();
```

Having two users uploading on the same second is not unheard of especially when dealing with slightly higher traffic websites

**Comment by steveclifton** [comment]
Thanks have included
