### ISSUE TITLE
Datepicker auto opening 

### ISSUE THREAD

**Issue by steveclifton** [steveclifton/ArcheryOSA#4]
Each time I change to another window, then come back to the webpage, the datepicker auto opens. I would like to disable this from opening without user clicking

![image](https://user-images.githubusercontent.com/14119296/31314560-fbaa050a-ac5f-11e7-8f99-9d63ba943ebc.png)

https://github.com/steveclifton/ArcheryOSA/blob/master/resources/views/auth/events/updateevent.blade.php

**Comment by mankutila** [comment]
I'll help you with this)

**Comment by phase06** [comment]
let me try to fix it

**Comment by phase06** [comment]
#9 please consider my PR

**Comment by steveclifton** [comment]
Good job that seems to have fixed it thanks!
