### ISSUE TITLE
HTML fixes

### ISSUE THREAD

**Issue by steveclifton** [steveclifton/ArcheryOSA#6]
There are lots of little issues with markup in the various views! 

Any legit updates will be approved and appreciated 👍

**Comment by BHRunkel19** [comment]
@steveclifton I can give this a go!

**Comment by steveclifton** [comment]
go for it 👍

**Comment by DhariniJeeva** [comment]
Can I try this?

**Comment by steveclifton** [comment]
Find anything that upgrades the code :D
